version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy  # ✅ wait until DB is ready
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/shopfinder
      - COOKIE_KEY=shopNear_

  db:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shopfinderdocker
    healthcheck:  # ✅ this ensures the DB is fully started before backend tries to connect
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
