version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      typesense:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/shopfinderdocker
      - COOKIE_KEY=shopNear_
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz

  db:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shopfinderdocker
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  typesense:
    image: typesense/typesense:0.24.1
    ports:
      - "8108:8108"
    command: >
      --data-dir /data
      --api-key=xyz
      --enable-cors
    volumes:
      - typesense_data:/data

volumes:
  postgres_data:
  typesense_data:
